# -Dspring.profiles.active 옵션으로 profiles 선택할 수 있다.
server:
  port: 8000
protest:
  message: This is default profiles msg
  port: 8000

---

spring:
  profiles: develop
server:
  port: 8100
protest:
  message: This is develop profiles data
  port: 8100

---

spring:
  profiles: production
server:
  port: 8200
protest:
  message: This is production profiles data
  port: 8200